# Generated by Django 4.1 on 2022-08-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_restaurant_list',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
