#
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# [START django_app]
# [START gaestd_py_django_app_yaml]
runtime: python39

env_variables:
  # This setting is used in settings.py to configure your ALLOWED_HOSTS
  APPENGINE_URL: https://foodie-355420.uc.r.appspot.com
  # https://cloud.google.com/appengine/docs/legacy/standard/python/connecting-vpc
  GAE_USE_SOCKETS_HTTPLIB : 'anyvalue'
# [END gaestd_py_django_app_yaml]
# [END django_app]

vpc_access_connector:
  name: projects/foodie-355420/locations/us-east4/connectors/foodie