# Generated by Django 4.1 on 2023-09-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='google_maps_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='google_maps_url',
            field=models.URLField(null=True),
        ),
    ]
